routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\MenuController;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;

// use Ramsey\Collection\Map\NamedParameterMap;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login')->middleware('guest');

Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', function () {
    Auth::logout();
    return redirect('/login');
})->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin.index');
    Route::resource('menu', MenuController::class);

    Route::get('/surat', [App\Http\Controllers\Master\SuratController::class, 'tblSurat'])->name('Daftar Surat');
    Route::get('/surat/add', [App\Http\Controllers\Master\SuratController::class, 'addSurat'])->name('Add Surat');
    Route::post('/surat/add', [App\Http\Controllers\Master\SuratController::class, 'tambahSurat'])->name('Tambah Surat');
    Route::get('/surat/{id}', [App\Http\Controllers\Master\SuratController::class, 'editSurat'])->name('Edit Surat');
    Route::post('/surat/{id}', [App\Http\Controllers\Master\SuratController::class, 'updateSurat'])->name('Update Surat');
    Route::put('/surat/{id}', [App\Http\Controllers\Master\SuratController::class, 'deleteSurat'])->name('Hapus Surat');


    Route::get('/subjek', [App\Http\Controllers\Master\SubjekController::class, 'tblSubjek'])->name('Daftar Subjek');
    Route::get('/subjek/add', [App\Http\Controllers\Master\SubjekController::class, 'addSubjek'])->name('Add Subjek');
    Route::post('/subjek/add', [App\Http\Controllers\Master\SubjekController::class, 'tambahSubjek'])->name('Tambah Subjek');
    Route::get('/subjek/{id}', [App\Http\Controllers\Master\SubjekController::class, 'editSubjek'])->name('Edit Subjek');
    Route::post('/subjek/{id}', [App\Http\Controllers\Master\SubjekController::class, 'updateSubjek'])->name('Update Subjek');
    Route::put('/subjek/{id}', [App\Http\Controllers\Master\SubjekController::class, 'deleteSubjek'])->name('Hapus Subjek');

    Route::get('/running', [App\Http\Controllers\Master\RunningController::class, 'tblRunning'])->name('Daftar Running');
    Route::get('/running/add', [App\Http\Controllers\Master\RunningController::class, 'addRunning'])->name('Add Running');
    Route::post('/running/add', [App\Http\Controllers\Master\RunningController::class, 'tambahRunning'])->name('Tambah Running');
    Route::get('/running/{id}', [App\Http\Controllers\Master\RunningController::class, 'editRunning'])->name('Edit Running');
    Route::post('/running/{id}', [App\Http\Controllers\Master\RunningController::class, 'updateRunning'])->name('Update Running');
    Route::put('/running/{id}', [App\Http\Controllers\Master\RunningController::class, 'deleteRunning'])->name('Hapus Running');


    Route::get('/epaper', [App\Http\Controllers\Epaper\EpaperController::class, 'tblEpaper'])->name('Daftar Epaper');
    Route::get('/epaper/add', [App\Http\Controllers\Epaper\EpaperController::class, 'addEpaper'])->name('Add Epaper');
    Route::post('/epaper/add', [App\Http\Controllers\Epaper\EpaperController::class, 'tambahEpaper'])->name('Tambah Epaper');
    Route::get('/epaper/{id}', [App\Http\Controllers\Epaper\EpaperController::class, 'editEpaper'])->name('Edit Epaper');
    Route::post('/epaper/{id}', [App\Http\Controllers\Epaper\EpaperController::class, 'updateEpaper'])->name('Update Epaper');
    Route::put('/epaper/{id}', [App\Http\Controllers\Epaper\EpaperController::class, 'deleteEpaper'])->name('Hapus Epaper');

});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $connection = 'db_akd';
    protected $table = 'menu';

    protected $fillable = [
        'id',
        'title',
        'urutan',
        'status_sileg',
        'status',
        'user_input',
        'tanggal_input',
        'user_update',
        'tanggal_update',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($audit) {
            $audit->user_input = auth()->user()->nama;
            $audit->tanggal_input = now();
        });

        static::updating(function ($audit) {
            $audit->user_update = auth()->user()->nama;
            $audit->tanggal_update = now();
        });
    }


    public $timestamps = false;
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Menu;

class MenuController extends Controller
{
    public function index()
    {
        $menus = Menu::where('status', 1)->orderBy('id', 'desc')->get();
        return view('menu.index', compact('menus'));
    }

    public function create()
    {
        return view('menu.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();

        $data['tanggal_input'] = now();
        $data['status'] = 1;

        $lastId = Menu::create($data);

        return redirect()->route('menu.index')
            ->with('success', 'Daftar menu berhasil ditambahkan.');
    }

    public function edit($id)
    {
        $menu = Menu::findOrFail($id);
        return view('menu.edit', compact('menu'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();

        $data['tanggal_update'] = now();
        $data['status'] = 1;

        $menu = Menu::findOrFail($id);
        $menu->update($data);

        return redirect()->route('menu.index')
            ->with('success', 'Daftar menu berhasil diperbarui.');
    }

    public function destroy($id)
    {
        $menu = Menu::findOrFail($id);
        $menu->status = 9;
        $menu->save();

        return redirect()->route('menu.index')
            ->with('success', 'Menu berhasil dihapus.');
    }
}

resources/views/menu/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <div>
            <ol class="breadcrumb fs-sm mb-1">
                <li class="breadcrumb-item">Menu</li>
                <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
            </ol>
            <h4 class="main-title mb-0">Tambah Menu</h4>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="mb-3">
                <form action="{{ route('menu.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="mb-3">
                        <label for="menu" class="form-label fw-bold">Menu</label>
                        <div class="d-flex flex-row gap-2">
                            <input required type="text" class="form-control w-50" id="menu" name="title"
                                placeholder="Masukan menu">
                            <font style="color: red; display: flex; align-items: center; padding: 0;">*</font>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="status-sileg" class="form-label fw-bold">Status SILEG</label>
                        <div style="width: 100%;">
                            <input type="checkbox" class="form-check-input" id="status-sileg"
                                onclick="updateStatusSileg()">
                        </div>
                        <input type="hidden" name="status_sileg" id="status-sileg-hidden" value="0">
                    </div>

                    <input type="submit" value="Simpan" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        function updateStatusSileg() {
            var checkbox = document.getElementById('status-sileg');
            var hiddenInput = document.getElementById('status-sileg-hidden');

            hiddenInput.value = checkbox.checked ? 1 : 0;
        }
    </script>
@endpush

resources/views/menu/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <div>
            <ol class="breadcrumb fs-sm mb-1">
                <li class="breadcrumb-item">Menu</li>
                <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
            </ol>
            <h4 class="main-title mb-0">Edit Menu</h4>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                    {{ session('success') }}
                </div>
                <script>
                    setTimeout(function() {
                        document.getElementById('success-alert').remove();
                    }, 3000);
                </script>
            @endif
            <div class="mb-3">
                <form action="{{ route('menu.update', $menu->id) }}" method="POST"
                    enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="mb-3">
                        <label for="menu" class="form-label fw-bold">Menu</label>
                        <div class="d-flex flex-row gap-2">
                            <input required type="text" class="form-control w-50" id="menu" name="menu"
                                placeholder="Masukan menu" value="{{ $menu->menu }}">
                            <font style="color: red; display: flex; align-items: center; padding: 0;">*</font>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="status-sileg" class="form-label fw-bold">Status SILEG</label>
                        <div style="width: 100%;">
                            <input type="checkbox" class="form-check-input" id="status-sileg"
                                onclick="updateStatusSileg()">
                        </div>
                        <input type="hidden" name="status_sileg" id="status-sileg-hidden" value="0">
                    </div>

                    <input type="submit" value="Simpan Perubahan" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        function updateStatusSileg() {
            var checkbox = document.getElementById('status-sileg');
            var hiddenInput = document.getElementById('status-sileg-hidden');

            hiddenInput.value = checkbox.checked ? 1 : 0;
        }
    </script>
@endpush

resources/views/menu/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4 ">
        <div>
            <ol class="breadcrumb fs-sm mb-1 ">
                <li class="breadcrumb-item">Menu</li>
                <li class="breadcrumb-item active" aria-current="page">Info Menu</li>
            </ol>
            <h4 class="main-title mb-0">Daftar Menu</h4>
        </div>
        <div>
            <a href="{{ route('menu.create') }}" class="btn btn-success">
                <i class="ri-pencil-line"></i> Tambah Menu
            </a>
        </div>
    </div>

    <div class="card ">
        <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                    {{ session('success') }}
                </div>
                <script>
                    setTimeout(function() {
                        document.getElementById('success-alert').remove();
                    }, 3000);
                </script>
            @endif

            <div class="table-responsive">
                <table id="tableGrid3">
                    <thead>
                        <tr>
                            <th scope="col" class="p-1 text-center" style="width: 5%;">No</th>
                            <th scope="col" class="p-1 text-center" style="width: 50%;">Menu</th>
                            <th scope="col" class="p-1 text-center" style="width: 20%;">Status SILEG</th>
                            <th scope="col" class="p-1 text-center" style="width: 25%;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($menus as $i => $menu)
                            <tr>
                                <td class="text-center">{{ $i + 1 }}</td>
                                <td>{{ $menu->title }}</td>
                                @if ($menu->status_sileg == 1)
                                    <td class="text-center">Ya</td>
                                @else
                                    <td class="text-center">Tidak</td>
                                @endif
                                <td class="text-center">
                                    <a href="{{ route('menu.edit', $menu->id) }}"
                                        class="btn btn-primary p-1">
                                        <i class="ri-edit-2-line"></i> Edit
                                    </a>
                                    <form action="{{ route('menu.destroy', $menu->id) }}"
                                        method="POST" style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger p-1">
                                            <i class="ri-delete-bin-line"></i> Hapus
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection